nba_teams = [
    "Atlanta Hawks",
    "Boston Celtics",
    "Brooklyn Nets",
    "Charlotte Hornets",
    "Chicago Bulls",
    "Cleveland Cavaliers",
    "Dallas Mavericks",
    "Denver Nuggets",
    "Detroit Pistons",
    "Golden State Warriors",
    "Houston Rockets",
    "Indiana Pacers",
    "Los Angeles Clippers",
    "Los Angeles Lakers",
    "Memphis Grizzlies",
    "Miami Heat",
    "Milwaukee Bucks",
    "Minnesota Timberwolves",
    "New Orleans Pelicans",
    "New York Knicks",
    "Oklahoma City Thunder",
    "Orlando Magic",
    "Philadelphia 76ers",
    "Phoenix Suns",
    "Portland Trail Blazers",
    "Sacramento Kings",
    "San Antonio Spurs",
    "Toronto Raptors",
    "Utah Jazz",
    "Washington Wizards",
    "Charlotte Bobcats",
    "Seattle Supersonics",
    "Atlanta Blackhawks",
    "Washington Bullets",
    "Cincinatti Royals",
    "Syracuse Nationals",
    "Chicago Zephyrs",
    "Chicago Packers",
    "Buffalo Braves",
]

city_list = [
    "Louisville",
    "Oorang",
    "Los Angeles",
    "Dallas",
    "Detroit",
    "Racine",
    "Tennessee",
    "Green Bay",
    "Phil-Pitt",
    "Rochester",
    "Atlanta",
    "Providence",
    "Staten Island",
    "Miami",
    "Cincinnati",
    "Pittsburgh",
    "Kansas City",
    "New York",
    "Tampa Bay",
    "Newark",
    "Chicago",
    "Denver",
    "Boston",
    "St. Louis",
    "Jacksonville",
    "Columbus",
    "Evansville",
    "Cleveland",
    "Akron",
    "Baltimore",
    "Kenosha",
    "Frankford",
    "Hartford",
    "Las Vegas",
    "Milwaukee",
    "Washington",
    "Canton",
    "Carolina",
    "Hammond",
    "Indianapolis",
    "Houston",
    "Rock Island",
    "Minnesota",
    "New Orleans",
    "Card-Pitt",
    "New England",
    "Seattle",
    "Brooklyn",
    "Dayton",
    "Indianapolis,Los Angeles",
    "Minneapolis",
    "San Francisco",
    "Arizona",
    "Philadelphia",
    "Buffalo",
    "Syracuse",
    "Troy",
    "Worcester",
    "Pittsburg",
    "California",
    "Oakland",
    "Montreal",
    "San Diego",
    "Texas",
    "Toronto",
    "Colorado",
    "Florida",
    "Anaheim",
    "Vancouver",
    "Edmonton",
    "Quebec",
    "Winnipeg",
    "Calgary",
    "New Jersey",
    "San Jose",
    "Ottawa",
    "Phoenix",
    "Nashville",
    "Vegas",
]


place_to_area = {
    "Phil-Pitt": "Philadelphia",
    "Card-Pitt": "Pittsburgh",
    "Evansville": "Chicago",
    "Oorang": "Ohio",
    "Worcester": "Boston",
    "Kenosha": "Chicago",
    "Vegas": "Las Vegas",
    "Troy": "Ohio",
    "Rock Island": "Chicago",
    "Rochester": "New York",
    "Racine": "Milwaukee",
    "Pittsburg": "Pittsburgh",
    "Canton": "Ohio",
    "Minneapolis": "Minnesota",
    "Hammond": "Ohio",
    "Akron": "Ohio",
    "Staten Island": "New York",
    "Newark": "New York",
    "Dayton": "Ohio",
    "Frankford": "Ohio",
    "Louisville": "Louisville",
    "Syracuse": "New York",
    "Providence": "Providence",
    "Quebec": "Quebec",
    "Hartford": "Hartford",
    "Nashville": "Tennessee",
    "Columbus": "Ohio",
    "Jacksonville": "Jacksonville",
    "Winnipeg": "Winnipeg",
    "Ottawa": "Ottawa",
    "San Jose": "San Francisco",
    "Anaheim": "Los Angeles",
    "California": "California",
    "New Jersey": "New York",
    "Calgary": "Calgary",
    "Edmonton": "Edmonton",
    "Florida": "Miami",
    "Texas": "Texas",
    "Vancouver": "Vancouver",
    "Carolina": "Carolina",
    "San Diego": "San Diego",
    "Oakland": "San Francisco",
    "New Orleans": "New Orleans",
    "Colorado": "Colorado",
    "Tennessee": "Tennessee",
    "Las Vegas": "Las Vegas",
    "New England": "Boston",
    "Phoenix": "Arizona",
    "Indianapolis": "Indianapolis",
    "Miami": "Miami",
    "Tampa Bay": "Tampa Bay",
    "Green Bay": "Green Bay",
    "Denver": "Colorado",
    "Montreal": "Montreal",
    "Baltimore": "Baltimore",
    "Brooklyn": "New York",
    "Milwaukee": "Milwaukee",
    "Arizona": "Arizona",
    "Houston": "Houston",
    "Seattle": "Seattle",
    "Kansas City": "Kansas City",
    "Dallas": "Dallas",
    "Toronto": "Toronto",
    "Buffalo": "Buffalo",
    "San Francisco": "San Francisco",
    "Cincinnati": "Cincinnati",
    "Minnesota": "Minnesota",
    "Atlanta": "Atlanta",
    "St. Louis": "St. Louis",
    "Cleveland": "Cleveland",
    "Pittsburgh": "Pittsburgh",
    "Washington": "Washington",
    "Boston": "Boston",
    "Detroit": "Detroit",
    "Philadelphia": "Philadelphia",
    "Los Angeles": "Los Angeles",
    "Chicago": "Chicago",
    "New York": "New York",
}
